service: nftService

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 120

functions:
  deployContract:
    handler: src/deployContract.handler
    events:
      - httpApi: POST /deployContract
  basicMint:
    handler: src/basicMint.handler
    events:
      - httpApi: POST /basicMint
  batchMint:
    handler: src/batchMint.handler
    events:
      - httpApi: POST /batchMint
  changeUri:
    handler: src/basicChangeUri.handler
    events:
      - httpApi: POST /basicChangeUri
  createMetadataFiles:
    handler: src/createMetadataFiles.handler
    events:
      - httpApi: POST /createMetadataFiles
  editMetadataFiles:
    handler: src/editMetadataFiles.handler
    events:
      - httpApi: POST /editMetadataFiles
  convertMetadataFolderToIpfs:
    handler: src/convertMetadataFolderToIpfs.handler
    events:
      - httpApi: POST /convertMetadataFolderToIpfs
  getMetadataHistory:
    handler: src/getMetadataHistory.handler
    events:
      - httpApi: POST /getMetadataHistory

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-offline
